[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:330 checking whether the connectivity to the database is working
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:336 confirming that the primary is not isolated from the cluster
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:340 Cutting network for postgresql-k8s/2
[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.4.4    unsupported  02:43:02Z

App                  Version  Status  Scale  Charm                Channel      Rev  Address         Exposed  Message
postgresql-k8s       14.12    active      3  postgresql-k8s                      0  10.152.183.142  no       
postgresql-test-app           active      1  postgresql-test-app  latest/edge  194  10.152.183.173  no       received database credentials of the first database

Unit                    Workload  Agent  Address       Ports  Message
postgresql-k8s/0*       active    idle   10.1.198.139         Primary
postgresql-k8s/1        active    idle   10.1.198.140         
postgresql-k8s/2        active    idle   10.1.198.141         Primary
postgresql-test-app/0*  active    idle   10.1.198.142         received database credentials of the first database

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:


[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...