[32mINFO    [0m pytest_operator.plugin:plugin.py:766 Connecting to existing model microk8s-localhost:test on unspecified cloud
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/s3-integrator-77
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/self-signed-certificates-155
[32mINFO    [0m juju.model:model.py:2098 Deploying local:jammy/postgresql-k8s-0
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s-aws/0 [allocating] waiting: installing agent
  postgresql-k8s-aws/1 [allocating] waiting: installing agent
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s-aws/0 [allocating] waiting: agent initialising
  postgresql-k8s-aws/1 [allocating] waiting: agent initialising
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s-aws/0 [executing] maintenance: installing charm software
  postgresql-k8s-aws/1 [executing] waiting: awaiting for cluster to start
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s-aws/0 [executing] unknown: 
  postgresql-k8s-aws/1 [executing] waiting: awaiting for primary endpoint to be ready
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s-aws/0 [idle] unknown: 
  postgresql-k8s-aws/1 [executing] waiting: awaiting for primary endpoint to be ready
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s-aws/0 [idle] unknown: 
  postgresql-k8s-aws/1 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s-aws/0 [idle] waiting: awaiting for cluster to start
  postgresql-k8s-aws/1 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s-aws/0 [idle] waiting: awaiting for cluster to start
  postgresql-k8s-aws/1 [idle] maintenance: Executing restart operation
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s-aws/0 [idle] waiting: awaiting for cluster to start
  postgresql-k8s-aws/1 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s-aws/0 [idle] active: 
  postgresql-k8s-aws/1 [executing] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s-aws/1 [executing] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s-aws/0 [executing] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s-aws/0 [executing] active: 
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m integration.test_backups_pitr:test_backups_pitr.py:123 configuring S3 integrator for aws
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s-aws/0 [executing] active: 
  postgresql-k8s-aws/1 [executing] active: Primary
  s3-integrator/0 [executing] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s-aws/0 [idle] active: 
  postgresql-k8s-aws/1 [executing] maintenance: initialising stanza
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s-aws/0 [idle] active: 
  postgresql-k8s-aws/1 [executing] maintenance: initialising stanza
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s-aws/0 [idle] active: 
  postgresql-k8s-aws/1 [executing] maintenance: initialising stanza
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s-aws/0 [executing] active: 
  postgresql-k8s-aws/1 [executing] active: Primary
  s3-integrator/0 [executing] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s-aws/0 [idle] active: 
  postgresql-k8s-aws/1 [executing] maintenance: initialising stanza
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s-aws/0 [idle] active: 
  postgresql-k8s-aws/1 [idle] active: Primary
[32mINFO    [0m integration.test_backups_pitr:test_backups_pitr.py:144 creating a table in the database
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  s3-integrator/0 [idle] active: 
  self-signed-certificates/0 [idle] active: 
  postgresql-k8s-aws/0 [idle] active: 
  postgresql-k8s-aws/1 [idle] active: Primary
[32mINFO    [0m integration.test_backups_pitr:test_backups_pitr.py:155 creating a backup
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  s3-integrator/0 [idle] active: 
  self-signed-certificates/0 [idle] active: 
  postgresql-k8s-aws/0 [idle] active: 
  postgresql-k8s-aws/1 [executing] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s-aws/1 [idle] active: Primary
[32mINFO    [0m integration.test_backups_pitr:test_backups_pitr.py:164 listing the available backups
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  s3-integrator/0 [idle] active: 
  self-signed-certificates/0 [idle] active: 
  postgresql-k8s-aws/0 [idle] active: 
  postgresql-k8s-aws/1 [idle] active: Primary
[32mINFO    [0m integration.test_backups_pitr:test_backups_pitr.py:173 creating after-backup data in the database
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s-aws (waiting for exactly 1 units, current : 2)
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s-aws (waiting for exactly 1 units, current : 2)
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s-aws/0 [idle] active: Primary
[32mINFO    [0m integration.test_backups_pitr:test_backups_pitr.py:203 restoring the backup with bad restore-to-time parameter
[32mINFO    [0m integration.test_backups_pitr:test_backups_pitr.py:213 restoring the backup with unreachable restore-to-time parameter
[32mINFO    [0m integration.test_backups_pitr:test_backups_pitr.py:218 waiting for the database charm to become blocked
[32mINFO    [0m integration.test_backups_pitr:test_backups_pitr.py:225 database charm become in blocked state, as supposed to be with unreachable PITR parameter
[32mINFO    [0m integration.test_backups_pitr:test_backups_pitr.py:234 restoring the backup
[32mINFO    [0m integration.test_backups_pitr:test_backups_pitr.py:253 checking that the backup was correctly restored
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  s3-integrator/0 [idle] active: 
  self-signed-certificates/0 [idle] active: 
  postgresql-k8s-aws/0 [executing] blocked: Move restored cluster to another S3 bucket
[32mINFO    [0m integration.test_backups_pitr:test_backups_pitr.py:79 deleting the previously created backups
[32mINFO    [0m pytest_operator.plugin:plugin.py:903 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.4.5    unsupported  02:58:04Z

App            Version  Status  Scale  Charm          Channel        Rev  Address         Exposed  Message
s3-integrator           active      1  s3-integrator  latest/stable   77  10.152.183.121  no       

Unit              Workload  Agent  Address    Ports  Message
s3-integrator/0*  active    idle   10.1.53.8         

[32mINFO    [0m pytest_operator.plugin:plugin.py:909 Juju error logs:

unit-postgresql-k8s-aws-0: 02:51:06 ERROR unit.postgresql-k8s-aws/0.juju-log Restore failed: Bad restore-to-time format
unit-postgresql-k8s-aws-0: 02:52:18 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service get failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:52:18 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service patch failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:52:51 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service get failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:52:51 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service patch failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:53:14 ERROR unit.postgresql-k8s-aws/0.juju-log Restore failed: database service failed to reach point-in-time-recovery target. You can launch another restore with different parameters
unit-postgresql-k8s-aws-0: 02:53:14 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service get failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:53:14 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service patch failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:53:35 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service get failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:53:35 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service patch failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:53:46 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service get failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:53:46 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service patch failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:53:54 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service get failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:53:54 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service patch failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:54:05 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service get failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:54:05 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service patch failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:54:16 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service get failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:54:16 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service patch failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:54:28 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service get failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:54:28 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service patch failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:54:36 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service get failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:54:36 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service patch failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:54:47 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service get failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:54:47 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service patch failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:54:58 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service get failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:54:58 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service patch failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:55:07 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service get failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:55:07 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service patch failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:55:17 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service get failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:55:17 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service patch failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:55:25 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service get failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:55:25 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service patch failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:55:34 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service get failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:55:34 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service patch failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:55:46 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service get failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:55:46 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service patch failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:55:54 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service get failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:55:54 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service patch failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:56:04 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service get failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:56:04 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service patch failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:56:28 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service get failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:56:28 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service patch failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:56:45 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service get failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:56:45 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service patch failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:57:05 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service get failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:57:05 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service patch failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:57:07 ERROR unit.postgresql-k8s-aws/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-aws-0/charm/venv/ops/model.py", line 3213, in _run
    result = subprocess.run(args, **kwargs)  # type: ignore
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-postgresql-k8s-aws-0/secret-get', '--label', 'database-peers.postgresql-k8s-aws.unit', '--refresh', '--format=json')' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-aws-0/charm/venv/ops/model.py", line 3579, in secret_get
    result = self._run('secret-get', *args, return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-postgresql-k8s-aws-0/charm/venv/ops/model.py", line 3215, in _run
    raise ModelError(e.stderr) from e
ops.model.ModelError: ERROR secret "secret:ct4iidfmp25c7bjh4pl0" not found


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-aws-0/charm/./src/charm.py", line 2202, in <module>
    main(PostgresqlOperatorCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-postgresql-k8s-aws-0/charm/venv/ops/main.py", line 551, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-postgresql-k8s-aws-0/charm/venv/ops/main.py", line 424, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-postgresql-k8s-aws-0/charm/venv/ops/main.py", line 427, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-postgresql-k8s-aws-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 441, in wrap_init
    original_init(self, framework, *args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-k8s-aws-0/charm/./src/charm.py", line 235, in __init__
    jobs=self._generate_metrics_jobs(self.is_tls_enabled),
  File "/var/lib/juju/agents/unit-postgresql-k8s-aws-0/charm/./src/charm.py", line 1556, in is_tls_enabled
    return all(self.tls.get_tls_files())
  File "/var/lib/juju/agents/unit-postgresql-k8s-aws-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-postgresql-k8s-aws-0/charm/lib/charms/postgresql_k8s/v0/postgresql_tls.py", line 215, in get_tls_files
    ca = self.charm.get_secret(SCOPE, "ca")
  File "/var/lib/juju/agents/unit-postgresql-k8s-aws-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-postgresql-k8s-aws-0/charm/./src/charm.py", line 347, in get_secret
    if result := self.peer_relation_data(scope).fetch_my_relation_field(peers.id, key):
  File "/var/lib/juju/agents/unit-postgresql-k8s-aws-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1393, in fetch_my_relation_field
    if relation_data := self.fetch_my_relation_data([relation_id], [field], relation_name):
  File "/var/lib/juju/agents/unit-postgresql-k8s-aws-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1382, in fetch_my_relation_data
    data[relation.id] = self._fetch_my_specific_relation_data(relation, fields)
  File "/var/lib/juju/agents/unit-postgresql-k8s-aws-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 532, in wrapper
    return f(self, *args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-k8s-aws-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 2329, in _fetch_my_specific_relation_data
    self.component, self.secret_fields, relation, fields
  File "/var/lib/juju/agents/unit-postgresql-k8s-aws-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1966, in secret_fields
    self.static_secret_fields if self.static_secret_fields else self.current_secret_fields
  File "/var/lib/juju/agents/unit-postgresql-k8s-aws-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1985, in current_secret_fields
    if content := self._get_group_secret_contents(relation, group):
  File "/var/lib/juju/agents/unit-postgresql-k8s-aws-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 2316, in _get_group_secret_contents
    result = super()._get_group_secret_contents(relation, group, secret_fields)
  File "/var/lib/juju/agents/unit-postgresql-k8s-aws-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1120, in _get_group_secret_contents
    secret_data := secret.get_content()
  File "/var/lib/juju/agents/unit-postgresql-k8s-aws-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 746, in get_content
    self._secret_content = self.meta.get_content(refresh=True)
  File "/var/lib/juju/agents/unit-postgresql-k8s-aws-0/charm/venv/ops/model.py", line 1409, in get_content
    self._content = self._backend.secret_get(id=self.id, label=self.label, refresh=refresh)
  File "/var/lib/juju/agents/unit-postgresql-k8s-aws-0/charm/venv/ops/model.py", line 3582, in secret_get
    raise SecretNotFoundError() from e
ops.model.SecretNotFoundError
unit-postgresql-k8s-aws-0: 02:57:07 ERROR juju.worker.uniter.operation hook "update-status" (via hook dispatching script: dispatch) failed: exit status 1
controller-0: 02:57:09 ERROR juju.worker.caasapplicationprovisioner.runner exited "postgresql-k8s-aws": getting OCI image resources: unable to fetch OCI image resources for postgresql-k8s-aws: application "postgresql-k8s-aws" dying or dead
unit-postgresql-k8s-aws-0: 02:57:14 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service get failed: services "postgresql-k8s-aws" not found
unit-postgresql-k8s-aws-0: 02:57:14 ERROR unit.postgresql-k8s-aws/0.juju-log Kubernetes service patch failed: services "postgresql-k8s-aws" not found

[32mINFO    [0m pytest_operator.plugin:plugin.py:991 Forgetting model main...